### PR TITLE
Update README with correct syntax for register

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
- Addresses #19
- `stencila::register()` does not have an effect.

Signed-off-by: Achintya Rao <achintya.rao@cern.ch>

### CODE REVIEW

**Comment by nokome** [comment]
Thanks for this @RaoOfPhysics. We also need to make `register()` give a feedback message like you suggested before. Perhaps: 

```r
> stencila:::register()
"Stencila for R registered in ~/.stencila/hosts"
```

Would love a PR (or issue) for that :smirk: !

**Comment by RaoOfPhysics** [comment]
Would love to, but I don't know where to start! :( And a little too busy right now with thesis things. I'm happy to review content or help with documentation, though!

**Comment by nokome** [comment]
No worries, I was being a little cheeky fishing :fish: for more contribs :) Have made an issue https://github.com/stencila/r/issues/24 . Best wishes for your thesis!

**Comment by RaoOfPhysics** [comment]
I would genuinely love to contribute. :) My coding skillz are not up to scratch, but I can definitely help with documentation etc.

**Pull request merged**
